version: '2' # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 60
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          patterns:
            - "**/*.ts"
          exclude_patterns:
            - "**/*.d.ts"
          mass_threshold: 65
          filters:
            - "(.*?)@(Module|Controller|Injectable|Catch|ExceptionFilter|Middleware|NestMiddleware|Pipe|UsePipes|UseGuards|UseInterceptors|UseFilters)\\(.*?\\)"
            - "(.*?)@(Get|Post|Put|Delete|Patch|Options|Head|All)\\(.*?\\)"
            - "(.*?)@(Param|Query|Body|Headers|Req|Res)\\(.*?\\)"
            - "(.*?)@(ObjectType|InputType|Headers|Req|Res)\\(.*?\\)"
            - "(.*?)@Field\\((.*?) => (.*?)\\)"