version: '2.0'

services:
  api:
    container_name: ep-api
    build: .
    ports:
      - "5000:5000"
    volumes: # volumes for dev only
      - .:/usr/ep-api

  database:
    container_name: ep-db
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5432:5432"
