module.exports = {
  apps: [
    {
      name: 'ep-api',
      script: 'dist/src/main.js',
      watch: false,
      time: true,
      instances: 'max',
      exec_mode: 'cluster',
      ignore_watch: ['[/\\]./', 'uploads'],
      restart_delay: 10000,
      watch_delay: 10000,
      cwd: process.cwd(),
      log_type: 'json',
      error_file: './logs/api-error.json',
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      max_memory_restart: '2600M',

      env_development: {
        API_LEVEL: 'dev',
        max_memory_restart: '768M',
      },
    },
    {
      name: 'indexer-service',
      script: 'pnpm console indexer -l true',
      args: 'indexer',
      watch: false,
      time: true,
      ignore_watch: ['[/\\]./', 'uploads'],
      watch_delay: 10000,
      cwd: process.cwd(),
      log_type: 'json',
      error_file: `./logs/indexer-error.json`,
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '600M',
    },
    {
      name: 'notification-service',
      script: 'pnpm console-mail notifications -l true',
      args: 'notifications',
      watch: false,
      time: true,
      ignore_watch: ['[/\\]./', 'uploads'],
      watch_delay: 10000,
      cwd: process.cwd(),
      log_type: 'json',
      error_file: `./logs/notification-error.json`,
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '600M',
    },
    {
      name: 'bulk-translate-korean',
      script: 'dist/src/main.js',
      args: 'translate:bulk-korean',
      watch: false,
      time: true,
      autorestart: false, // Don't auto-restart after completion
      ignore_watch: ['[/\\]./', 'uploads'],
      watch_delay: 10000,
      cwd: process.cwd(),
      log_type: 'json',
      error_file: `./logs/translation-error.json`,
      out_file: `./logs/translation-out.json`,
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      max_memory_restart: '1G',

      env_development: {
        API_LEVEL: 'dev',
      },
    },
  ],
}
