export const nftIds = [
  { coingeckoId: 'clonex', wikiId: 'clone-x' },
  { coingeckoId: 'doodles-official', wikiId: 'doodles' },
  { coingeckoId: 'cyberbrokers-v3', wikiId: 'cyberbrokers' },
  { coingeckoId: 'quirkies-originals', wikiId: 'quirkies' },
  { coingeckoId: 'murakami-flowers-official', wikiId: 'murakamiflowers' },
  {
    coingeckoId: 'forgotten-runes-wizards-cult',
    wikiId: 'forgotten-runes',
  },
  { coingeckoId: 'onchainmonkey', wikiId: 'onchain-monkey' },
  { coingeckoId: 'mooncats-acclimated', wikiId: 'mooncats' },
  {
    coingeckoId: 'psychedelics-anonymous-genesis',
    wikiId: 'psychedelics-anonymous',
  },
  { coingeckoId: '0n1force', wikiId: '0n1-force' },
  { coingeckoId: 'voxels-formerly-cryptovoxels', wikiId: 'cryptovoxels' },
  { coingeckoId: 'habbo-avatars', wikiId: 'habbo-avatar' },
  { coingeckoId: 'worldwide-webb-land', wikiId: 'worldwide-webb' },
  { coingeckoId: 'project-nanopass', wikiId: 'nanopass' },
  { coingeckoId: 'zed-run-legacy', wikiId: 'zed-run' },
  { coingeckoId: 'cryptoon-goonz', wikiId: 'cryptoongoonz' },
  {
    coingeckoId: 'tom-sachs-rocket-factory-rockets',
    wikiId: 'tom-sachs-rocket-factory',
  },
  { coingeckoId: 'ragnarok-meta', wikiId: 'ragnarok-meta-nft' },
  { coingeckoId: 'stepn-shoeboxes', wikiId: 'stepn' },
  { coingeckoId: 'bullsontheblock', wikiId: 'bulls-on-the-block' },
  { coingeckoId: 'coolman-s-universe', wikiId: 'coolmans-universe' },
  { coingeckoId: 'jungle-freaks-genesis', wikiId: 'jungle-freaks' },
  { coingeckoId: 'r-planet-genesis-collection', wikiId: 'r-planet' },
  { coingeckoId: 'the-cryptodads', wikiId: 'cryptodads' },
  { coingeckoId: 'woodies-generative-characters', wikiId: 'woodies' },
  { coingeckoId: 'cupcat-nft', wikiId: 'cupcats' },
  { coingeckoId: 'the-yakuza-cats-society', wikiId: 'yakuza-cats-society' },
  {
    coingeckoId: 'league-of-kingdoms-ethereum',
    wikiId: 'league-of-kingdoms',
  },
  { coingeckoId: 'ethernity-master', wikiId: 'ethernity' },
  { coingeckoId: 'gods-unchained-collectibles', wikiId: 'gods-unchained' },
  { coingeckoId: 'superplastic-headtripz', wikiId: 'superplastic' },
  { coingeckoId: 'my-curio-cards', wikiId: 'curio-cards' },
  { coingeckoId: 'shinsekai-portal', wikiId: 'shinsekai' },
  { coingeckoId: 'the-meta-key', wikiId: 'metakey' },
]

export const cryptocurrencyIds = [
  { coingeckoId: 'binancecoin', wikiId: 'binance-coin' },
  { coingeckoId: 'usd-coin', wikiId: 'usdc' },
  { coingeckoId: 'cardano', wikiId: 'cardano-ada' },
  { coingeckoId: 'matic-network', wikiId: 'matic' },
  { coingeckoId: 'avalanche-2', wikiId: 'avalanche' },
  { coingeckoId: 'the-open-network', wikiId: 'the-open-network-toncoin' },
  { coingeckoId: 'internet-computer', wikiId: 'internet-computer-icp' },
  { coingeckoId: 'hedera-hashgraph', wikiId: 'hedera' },
  { coingeckoId: 'frax', wikiId: 'frax-stablecoin' },
  { coingeckoId: 'klay-token', wikiId: 'klaytn' },
  { coingeckoId: 'gatechain-token', wikiId: 'gatechain' },
  { coingeckoId: 'btse-token', wikiId: 'btse' },
  { coingeckoId: 'enjincoin', wikiId: 'enjin' },
  { coingeckoId: 'mask-network', wikiId: 'mask' },
  { coingeckoId: 'olympus', wikiId: 'ohm' },
  { coingeckoId: 'compound-governance-token', wikiId: 'compound' },
  { coingeckoId: 'golem', wikiId: 'golem-network' },
  { coingeckoId: 'celsius-degree-token', wikiId: 'celsius-network' },
  { coingeckoId: 'iostoken', wikiId: 'iost' },
  { coingeckoId: 'just', wikiId: 'just-foundation' },
  { coingeckoId: 'moonbeam', wikiId: 'moonbeam-network' },
  { coingeckoId: 'energy-web-token', wikiId: 'energy-web' },
  { coingeckoId: 'coinex-token', wikiId: 'coinex' },
  { coingeckoId: 'zencash', wikiId: 'horizen' },
  { coingeckoId: 'platoncoin', wikiId: 'platon' },
  { coingeckoId: 'fx-coin', wikiId: 'function-x' },
  { coingeckoId: 'aragon', wikiId: 'aragon-court' },
  { coingeckoId: 'lukso-token', wikiId: 'lukso' },
  { coingeckoId: 'nervos-network', wikiId: 'nervos' },
  { coingeckoId: 'everipedia', wikiId: 'iq' },
  { coingeckoId: 'iexec-rlc', wikiId: 'iexec' },
  { coingeckoId: 'pha', wikiId: 'phala-network' },
  { coingeckoId: 'mxc', wikiId: 'mxc-foundation' },
  { coingeckoId: 'chromaway', wikiId: 'chromia' },
  { coingeckoId: 'quark-chain', wikiId: 'quarkchain' },
  { coingeckoId: 'conflux-token', wikiId: 'conflux' },
  { coingeckoId: 'chronobank', wikiId: 'chronotech' },
  { coingeckoId: 'liquity', wikiId: 'liquidity-network' },
  { coingeckoId: 'cvault-finance', wikiId: 'cvaultfinance' },
  { coingeckoId: 'moonriver', wikiId: 'moonriver-network' },
  { coingeckoId: 'fei-usd', wikiId: 'fei-protocol' },
  { coingeckoId: 'fetch-ai', wikiId: 'fetchai' },
  { coingeckoId: 'dawn-protocol', wikiId: 'dawn' },
  { coingeckoId: 'meter', wikiId: 'meter-governance' },
  {
    coingeckoId: 'btc-standard-hashrate-token',
    wikiId: 'bitcoin-standard-hashrate-token',
  },
  { coingeckoId: 'hshare', wikiId: 'hypercash' },
  { coingeckoId: 'bitshares', wikiId: 'biid:tshares' },
  { coingeckoId: 'zcoin', wikiId: 'firo' },
  { coingeckoId: 'mirror-protocol', wikiId: 'mirror' },
  { coingeckoId: 'fsn', wikiId: 'fusion' },
  { coingeckoId: 'marcopolo', wikiId: 'map-protocol' },
  { coingeckoId: 'amber', wikiId: 'ambrosus' },
  { coingeckoId: 'deus-finance-2', wikiId: 'deus-finance' },
  {
    coingeckoId: 'frax-price-index-share',
    wikiId: 'frax-price-index-share-fpis',
  },
  { coingeckoId: 'aleph', wikiId: 'alephim' },
  { coingeckoId: 'aventus', wikiId: 'aventus-protocol' },
  { coingeckoId: 'freeway', wikiId: 'freeway-token' },
  { coingeckoId: 'cream-2', wikiId: 'cream-finance' },
  { coingeckoId: 'grid', wikiId: 'gridplus' },
  { coingeckoId: 'nimiq-2', wikiId: 'nimiq' },
  { coingeckoId: 'get-token', wikiId: 'get-protocol' },
  { coingeckoId: 'lattice-token', wikiId: 'lattice' },
  { coingeckoId: 'quantum-resistant-ledger', wikiId: 'qrl' },
  { coingeckoId: 'hi-dollar', wikiId: 'hi' },
  { coingeckoId: 'everid', wikiId: 'everest' },
  { coingeckoId: 'strikecoin', wikiId: 'strikex' },
  { coingeckoId: 'cellframe', wikiId: 'cellframe-network' },
  { coingeckoId: 'rainicorn', wikiId: 'raini' },
  { coingeckoId: 'exeedme', wikiId: 'exeedme-xed' },
  { coingeckoId: 'nav-coin', wikiId: 'navcoin' },
  { coingeckoId: 'glitch-protocol', wikiId: 'glitch' },
  { coingeckoId: 'degenerator', wikiId: 'meme-dollarmeme' },
  { coingeckoId: 'digix-gold', wikiId: 'digix-gold-token' },
  { coingeckoId: 'matrix-ai-network', wikiId: 'matrix' },
  { coingeckoId: 'coinfirm-amlt', wikiId: 'amlt' },
  { coingeckoId: 'hempcoin-thc', wikiId: 'hempcoin' },
  { coingeckoId: 'peculium-2', wikiId: 'peculium' },
  { coingeckoId: 'blue', wikiId: 'blue-protocol' },
  { coingeckoId: 'lever-network', wikiId: 'leverj' },
  { coingeckoId: 'digitex-futures-exchange', wikiId: 'digitex' },
  { coingeckoId: 'b2bcoin-2', wikiId: 'b2bx' },
  { coingeckoId: 'beeco', wikiId: 'bee-token' },
  { coingeckoId: 'bodhi-network', wikiId: 'bodhi' },
  { coingeckoId: 'catcoin-cash', wikiId: 'catcoin' },
  { coingeckoId: 'frax-price-index', wikiId: 'frax-price-index-fpi' },
  { coingeckoId: 'ftx-token', wikiId: 'ftt' },
]
