name: Deploy to Prod
on: workflow_dispatch

jobs:
  deploy-to-prod:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Remove old SSH host key
        run: ssh-keygen -R ${{ secrets.HOST_PROD }}

      - name: Add new SSH host key
        run: ssh-keyscan -H ${{ secrets.HOST_PROD }} >> ~/.ssh/known_hosts

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.KEY_PROD }}
          port: ${{ secrets.PORT_PROD }}
          script: |
            cd ep-api
            git pull
            pnpm install --frozen-lockfile
            pnpm build:swc
            /home/ubuntu/.npm-global/bin/pm2 update
            
