name: Deploy
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checks Linting
        run: yarn lint

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Run tests
        run: yarn test

  build:
    name: build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Build Application
        run: yarn build

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ep-api
            git pull
            yarn
            pm2 update
