name: Deploy to Prod
on: workflow_dispatch

jobs:
  deploy-to-prod:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.KEY_PROD }}
          port: ${{ secrets.PORT_PROD }}
          script: |
            cd ep-api
            git pull
            pnpm install --frozen-lockfile
            pnpm build:swc
            pm2 update
            
