name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ep-api
            git pull
            yarn
            pm2 restart ecosystem.config.js --only ep-api
            while ! grep -m1 'Ready' < pm2 status ep-api; do
              sleep 1
            done
            pm2 restart ecosystem.config.js --only indexer-service
