name: Push checks
on: [push]
jobs:
  Push-Checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test
